### ISSUE TITLE
html_paged

### ISSUE THREAD

**Issue by atusy** [atusy/rmd-line-num#2]
Default behavior cause soft-wrapped codes starts at negative margins where line numbers are specified.

A following css will work around.

``` css
pre.numberSource a.sourceLine {
  left: 0em; /* -4em in default */
}
a.sourceLine {
  text-indent: -5em; /* -1em in default */
}
```

**Comment by atusy** [comment]
The above will affect code blocks without line numbers as well.

Better solution is

``` css
pre.numberSource a.sourceLine {
  left: 0em;
  text-indent: -5em
}
```
